FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --upgrade pip && pip install -r requirements.txt streamlit requests pillow

COPY app ./app
COPY models ./models

EXPOSE 8501

CMD ["streamlit", "run", "app/ui/streamlit_app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
